### ISSUE TITLE
panic: ./sample-apiserver flag redefined: log_dir

### ISSUE THREAD

**Issue by DavadDi** [kubernetes/sample-apiserver#6]
install on Mac, golang 1.8, by:
```
go get github.com/kubernetes/sample-apiserver
go build
```

```shell
./sample-apiserver
./sample-apiserver flag redefined: log_dir
panic: ./sample-apiserver flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc42001c0c0, 0x2f0f100, 0xc4202c2160, 0x24c7bf1, 0x7, 0x24fb2f0, 0x2f)
	/usr/local/go/src/flag/flag.go:793 +0x420
flag.(*FlagSet).StringVar(0xc42001c0c0, 0xc4202c2160, 0x24c7bf1, 0x7, 0x0, 0x0, 0x24fb2f0, 0x2f)
	/usr/local/go/src/flag/flag.go:696 +0x8b
flag.(*FlagSet).String(0xc42001c0c0, 0x24c7bf1, 0x7, 0x0, 0x0, 0x24fb2f0, 0x2f, 0xc4202c2140)
	/usr/local/go/src/flag/flag.go:709 +0x90
flag.String(0x24c7bf1, 0x7, 0x0, 0x0, 0x24fb2f0, 0x2f, 0x0)
	/usr/local/go/src/flag/flag.go:716 +0x69
k8s.io/sample-apiserver/vendor/github.com/golang/glog.init()
	/Users/diwh/go_study/src/k8s.io/sample-apiserver/vendor/github.com/golang/glog/glog_file.go:41 +0x14a
k8s.io/sample-apiserver/vendor/k8s.io/apimachinery/pkg/util/yaml.init()
	/Users/diwh/go_study/src/k8s.io/sample-apiserver/vendor/k8s.io/apimachinery/pkg/util/yaml/decoder.go:347 +0x71
k8s.io/sample-apiserver/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json.init()
	/Users/diwh/go_study/src/k8s.io/sample-apiserver/vendor/k8s.io/apimachinery/pkg/runtime/serializer/json/meta.go:64 +0x6c
k8s.io/sample-apiserver/vendor/k8s.io/apimachinery/pkg/runtime/serializer.init()
	/Users/diwh/go_study/src/k8s.io/sample-apiserver/vendor/k8s.io/apimachinery/pkg/runtime/serializer/protobuf_extension.go:49 +0x4e
k8s.io/sample-apiserver/vendor/k8s.io/apiserver/pkg/server.init()
	/Users/diwh/go_study/src/k8s.io/sample-apiserver/vendor/k8s.io/apiserver/pkg/server/serve.go:213 +0x9b
k8s.io/sample-apiserver/pkg/cmd/server.init()
	/Users/diwh/go_study/src/k8s.io/sample-apiserver/pkg/cmd/server/start.go:116 +0x58
main.init()
	/Users/diwh/go_study/src/github.com/kubernetes/sample-apiserver/main.go:43 +0x5d
```

**Comment by DavadDi** [comment]
should move sample-apiserver code to $GOPATH/k8s.io/kubernetes/sample-apiserver, and go build then ok.

**Comment by huzhengchuan** [comment]
I meet the same question, do you know why? @DavadDi
